### PR TITLE
Add package.swift and perform needed move of swift source file

### PR DESCRIPTION
**Pull request by lvnkmn**
regarding #194 

- [x] tested and works in SPM (Xcode 11)
- [x] tested and still works in CocoaPods

### CODE REVIEW

**Comment by lvnkmn** [comment]
Hi @chiahsien, 
Is there any chance this will be merged at some point?

**Comment by chiahsien** [comment]
Sorry for the late reply, does it also work on latest Xcode?

**Comment by ksloginov** [comment]
It does! (I'm using this PR's version with Xcode 11.3. Works fine)

**Comment by lvnkmn** [comment]
Awesome. Thanks!

**Pull request merged**
