### PR TITLE
Fix for issue when layout is rotated

### PR DESCRIPTION
**Pull request by joshleibsly**
@chiahsien We were having issues with the frame vs. bounds values when we rotated the view to support horizontal scrolling (admittedly, I've been meaning to look into adding this support, but we were in a time crunch :) ), and iOS sometimes has a discrepancy between frame and bounds values when adjusting the transform of a view. Let me know if you have any concerns here!

### CODE REVIEW

**Comment by chiahsien** [comment]
Thanks @joshleibsly !
Can you help to fix the Swift version as well?

**Comment by joshleibsly** [comment]
@chiahsien Yes, sure! I'll reopen this PR when I get to that later today.

**Comment by joshleibsly** [comment]
@chiahsien Should be good to go. Hopefully I can get around to actually adding horizontal scrolling soon :)

**Comment by chiahsien** [comment]
Good job! Thanks @joshleibsly :octocat:

**Comment by joonorbertsv** [comment]
@chiahsien 
When do you think you can make a new release that includes this fix?

**Comment by chiahsien** [comment]
This weekend or next weekdays.

**Comment by joonorbertsv** [comment]
Thanks!

**Comment by itdongbaojun** [comment]
@joshleibsly Hi，we want to know how to support horizontal scrolling？thks

**Pull request merged**
