### PR TITLE
Fix public headers path for ObjC SwiftPM target

### PR DESCRIPTION
**Pull request by master-nevi**
`publicHeadersPath` is relative to the `path` parameter. Without this change, no headers are exposed for consuming libraries and apps to use. I tested this in a sample project to verify. We may want to consider adding demo apps for the two swift package libraries to ensure this can't happen again.

### CODE REVIEW

**Comment by master-nevi** [comment]
cc @chiahsien

**Comment by nelson-dai-17Live** [comment]
> We may want to consider adding demo apps for the two swift package libraries to ensure this can't happen again.

Good idea!
I'm trying to use local SPM in demo apps but can't figure out a correct way to do that. Do you know how to do it?

**Comment by chiahsien** [comment]
> We may want to consider adding demo apps for the two swift package libraries to ensure this can't happen again.

Good idea!
I'm trying to use local SPM in demo apps but can't figure out a correct way to do that. Do you know how to do it? @master-nevi

**Comment by master-nevi** [comment]
Sure, do you want that in this PR or a separate PR?

**Comment by chiahsien** [comment]
In this same PR would be fine, thank you @master-nevi !

**Comment by master-nevi** [comment]
Hi @chiahsien . I figured you'd want to use the same demo apps if possible to avoid having a whole other set of sample code and xcode projects to maintain. So I just created a new target in each of the two demo projects that consumes the Swift Package and re-uses the demo-app code:

<p float="left">
Screen Shot 2021-12-02 at 1 06 13 PM

Screen Shot 2021-12-02 at 1 06 04 PM
</p>

Just to be sure I tested the current `Package.swift` and got an error (**which is expected**) from the CI:
Screen Shot 2021-12-02 at 12 43 27 PM

My update to the `Package.swift` fixes the error above.

**Comment by chiahsien** [comment]
LGTM! Thanks a lot for your help @master-nevi 👍

**Pull request merged**
